"""
Django settings for iphone project.

Generated by 'django-admin startproject' using Django 3.2.5.

from datetime import timedelta

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from datetime import timedelta
from pathlib import Path

from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

DEBUG = config('DEBUG', cast=bool)

# SECURITY WARNING: don't run with debug turned on in production!

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    
    
    'authentication.apps.AuthenticationConfig',
    'orders.apps.OrdersConfig',
    
    # TODO : all third party apps should be intalled after installations
    # TODO:  joser comes with it default urls must set up
    #  ===> Third Party Apps
    'rest_framework',
    'djoser',
    
    
]


AUTH_USER_MODEL = 'authentication.User'


# * custom validation errors
# * this will over write the way errors are been displayed on the django rest_framework admin panel

REST_FRAMEWORK = {
    'NON_FIELD_ERRORS_KEY': 'errors',
    
    # ! Authentication from the djoser
    'DEFAULT_AUTHENTICATION_CLASSES':(
        # ! this will allow us to create our jwt
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        
    )
}

# ! NOTE: PyJWT need to be install to downgrade to work with the current version so that our refresh token provided can be accepted by django.



# * to be able to control the (request header and things related to it) 

SIMPLE_JWT = {
   'AUTH_HEADER_TYPES': ('Bearer',),
   # ! ( timedelta() ) this specifies how long our token will be valid
   
    # todo (timedelta) was imported because of this
   'ACCESS_TOKEN_LIFETIME': timedelta(days = 1),
   'REFRESH_TOKEN_LIFETIME': timedelta(days = 1),
   
    # ! Adding this so that django will not throw 'Backlisted' has no attribute 'Objects'
   'BLACKLIST_AFTER_ROTATION': False,
   
}


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'iphone.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'iphone.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True



MEDIA_URL = '/url/api/iphones/'
# when you write ordinary BASE_DIR it will go to the base directory

MEDIA_ROOT = BASE_DIR

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
