# Generated by Django 3.2.5 on 2022-06-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='decription',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_images',
            field=models.ImageField(null=True, upload_to='images/iphones'),
        ),
    ]
