# Generated by Django 3.2.5 on 2022-06-19 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20220619_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_images',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
