# Generated by Django 3.2.5 on 2022-06-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_phone_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_colors',
            field=models.CharField(choices=[('ALPINE GREEN', 'alpine green'), ('SILVER', 'silver'), ('GOLD', 'gold'), ('GRAPHITE', 'graphite'), ('SIERRA BLUE', 'sierra blue')], default='silver', max_length=20),
        ),
    ]
