# Generated by Django 3.2.5 on 2022-06-19 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_phone_colors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='decription',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone_colors',
        ),
    ]
